apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinted-tryout-app-deployment
  labels:
    app: vinted-tryout-app
spec:
  replicas: 1 # You can change this as needed
  selector:
    matchLabels:
      app: vinted-tryout-app
  template:
    metadata:
      labels:
        app: vinted-tryout-app
    spec:
      containers:
      - name: vinted-tryout-app
        # This image line will be updated by the GitHub Actions workflow.
        # Ensure 'YOUR_DOCKERHUB_USERNAME' matches the ${{ secrets.DOCKER_USERNAME }} in your workflow.
        image: mariusmatonis/vinted-tryout-app:ccd64b3cb5921d8233dd008e23a5c6656c6ac90e
        ports:
        - containerPort: 5000 # Matches the EXPOSE port in your Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: vinted-tryout-app-service
spec:
  selector:
    app: vinted-tryout-app
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 5000 # The port your application listens on inside the container
  type: LoadBalancer # Change to ClusterIP, NodePort, etc., based on your K8s environment